{% set version = "0.4.2" %}

package:
  name: pandana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandana/pandana-{{ version }}.tar.gz
  sha256: 4069fc9dd220f0e189de4ac56d8e65cf97e4619544ce249466bd7f3abd7b41fe
  patches:
    - functional.patch
    - no_fopenmp.patch  # [osx]

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.25.2
    - numpy
  run:
    - {{ pin_compatible('numpy') }}
    - matplotlib >=1.3.1
    - numpy >=1.8.0
    - osmnet >=0.1.2
    - pandas >=0.17.0
    - python
    - requests >=2.0
    - scikit-learn >=0.18.1
    - pytables >=3.1.0

test:
  imports:
    - pandana
    - pandana.loaders
  requires:
    - pytest

about:
  home: https://udst.github.io/pandana
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: "Pandas Network Analysis - dataframes of network queries, quickly"

extra:
  recipe-maintainers:
    - ocefpaf
