{% set version = "0.4.3" %}

package:
  name: pandana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandana/pandana-{{ version }}.tar.gz
  sha256: 7832c9a8125f50b5da6372b644c11d1f91e731c3f5b9ad4810b0f912b71c032e

build:
  number: 0
  skip: True  # [win and vc<14]
  script:
    - export LDFLAGS="$LDFLAGS -fopenmp"  # [osx]
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - cython >=0.25.2
    - llvm-openmp  # [osx]
    - numpy
  run:
    - {{ pin_compatible('numpy') }}
    - llvm-openmp  # [osx]
    - matplotlib >=1.3.1
    - numpy >=1.8.0
    - osmnet >=0.1.2
    - pandas >=0.17.0
    - python
    - requests >=2.0
    - scikit-learn >=0.18.1
    - pytables >=3.1.0

test:
  imports:
    - pandana
    - pandana.cyaccess
    - pandana.loaders
  requires:
    - pytest

about:
  home: https://github.com/udst/pandana
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE.txt
  summary: "Pandas Network Analysis - dataframes of network queries, quickly"
  description: |
    Pandana performs hundreds of thousands of network queries in under a second (for walking-scale distances) using a Pandas-like API. The computations are parallelized for multi-core machines using an underlying C++ library.
  doc_url: https://udst.github.io/pandana
  dev_url: https://github.com/udst/pandana

extra:
  recipe-maintainers:
    - smmaurer
    - ocefpaf
