{% set version = "0.6.1" %}

package:
  name: pandana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandana/pandana-{{ version }}.tar.gz
  sha256: 7bcaf6e7bb3faccaf306846bf30838d8e94b3ebd58e971da8c3fe426f1f9288c

build:
  number: 0
  script:
    - export LDFLAGS="$LDFLAGS -fopenmp"  # [osx]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - cython >=0.25.2
    - llvm-openmp  # [osx]
    - numpy
  run:
    - {{ pin_compatible('numpy') }}
    - llvm-openmp  # [osx]
    - numpy >=1.8
    - pandas >=0.17
    - python
    - requests >=2.0
    - scikit-learn >=0.18
    - pytables >=3.1

test:
  imports:
    - pandana
    - pandana.cyaccess
    - pandana.loaders
  requires:
    - pytest

about:
  home: https://github.com/udst/pandana
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE.txt
  summary: Python library for network analysis
  description: |
    Pandana is a Python library for network analysis that uses contraction hierarchies to calculate super-fast travel accessibility metrics and shortest paths. The numerical code is in C++.
  doc_url: https://udst.github.io/pandana
  dev_url: https://github.com/udst/pandana

extra:
  recipe-maintainers:
    - smmaurer
    - ocefpaf
