travis:
  secure:
    BINSTAR_TOKEN: I3p4kDv37ReKRn3V7z0918N9vL3Y5WbWpOq3+y0+wTsIgC6Qfw/Xu6WgnJAsvBKffoJqchHq7Irf+G9w83oa+TaPrniW+mT+89G1h159DWhXEGlTf7GzSjG+vsKHxL7vyUFiwMw1NU1Fe3cKmPKLTtZXlvjU38cZLmJwoOdZ+7JpH2xO8vg+QJhbVvxpsT9Hebae9bK3g3swrZIixEMnHYOnSd7L0iL+LUvrMWcEsnhcpzo6Jt3Tr5PYErlhGcuPxNc2sXBsV8rpDYz7lGILb4KD8iwdcihQk7eOZom1h7Z3NzjswTd76avBvPE0aIaTkXVlzpR5iKiefSOiSJLqgmT3f7wucU4UwAqcgBZW86KKgztEHT0Rok+h9xwWxHFIZmEHtT8MyvpxVd/f+aEYemNWphgAcR3c3k9nTPS2XHTu0lA+jEge02vfE0nOFtpaMmtzPf2KS2vrHNAKmpbUGBzp8earF+nh5Qzr60r874zo7MBxWMFCxfsbJPqV+jFLLve221BqvGa9KVM9LMbUBZ3qTj8KilcqYb33AzFAx3l8PRtBFVlkpQ9qFnW+eO+CjdOCzdKq7hLBkfmRZB0h2tRMAoJCPbP8HMMYWOdquXk7vamdTliW6ttKm48JZUcd2wfuzU6+5Sq0miVNOrI5rvTfnXj9i56fSOj4vdG90gk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
